import Head from 'next/head'
import Image from 'next/image'

import type { NextPageContext } from 'next/dist/next-server/lib/utils'

import styles from '../styles/Home.module.css'

import {
  b2bCookieConsumer,
  b2bCookieSetter,
  execMiddlewareChains,
  phpSession,
} from '../middlewares'

export default function Home({ pokemon }: { pokemon: any }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js Pokemon!
        </h1>
        <div>
          {JSON.stringify(pokemon)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context: NextPageContext) {
  await execMiddlewareChains(context, [
    phpSession,
    b2bCookieSetter,
    b2bCookieConsumer
  ])

  const res = await fetch('https://nextjs-middleware-exporation.vercel.app/api/pokemon')
  const pokemon = await res.json()

  return { props: { pokemon } }
}